// Code generated by solo-kit. DO NOT EDIT.

//go:build solokit
// +build solokit

package v1

import (
	"context"
	"sync"
	"time"

	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
	"github.com/solo-io/solo-kit/pkg/api/v1/clients"
	"github.com/solo-io/solo-kit/pkg/api/v1/clients/factory"
	"github.com/solo-io/solo-kit/pkg/api/v1/clients/memory"
	"github.com/solo-io/solo-kit/pkg/api/v1/clients/kube/cache"
	skNamespace "github.com/solo-io/solo-kit/pkg/api/external/kubernetes/namespace"
	"github.com/solo-io/solo-kit/test/helpers"
)

var _ = Describe("KubeconfigsEventLoop", func() {
	var (
		ctx       context.Context
		namespace string
		emitter   KubeconfigsEmitter
		err       error
	)

	BeforeEach(func() {
		ctx = context.Background()

		kube := helpers.MustKubeClient()
		kubeCache, err := cache.NewKubeCoreCache(context.TODO(), kube)
		Expect(err).NotTo(HaveOccurred())
		resourceNamespaceLister := skNamespace.NewKubeClientCacheResourceNamespaceLister(kube, kubeCache)

		kubeConfigClientFactory := &factory.MemoryResourceClientFactory{
			Cache: memory.NewInMemoryResourceCache(),
		}
		kubeConfigClient, err := NewKubeConfigClient(ctx, kubeConfigClientFactory)
		Expect(err).NotTo(HaveOccurred())
		emitter = NewKubeconfigsEmitter(kubeConfigClient, resourceNamespaceLister)
	})
	It("runs sync function on a new snapshot", func() {
		_, err = emitter.KubeConfig().Write(NewKubeConfig(namespace, "jerry"), clients.WriteOpts{})
		Expect(err).NotTo(HaveOccurred())
		sync := &mockKubeconfigsSyncer{}
		el := NewKubeconfigsEventLoop(emitter, sync)
		_, err := el.Run([]string{namespace}, clients.WatchOpts{})
		Expect(err).NotTo(HaveOccurred())
		Eventually(sync.Synced, 5*time.Second).Should(BeTrue())
	})
})

type mockKubeconfigsSyncer struct {
	synced bool
	mutex  sync.Mutex
}

func (s *mockKubeconfigsSyncer) Synced() bool {
	s.mutex.Lock()
	defer s.mutex.Unlock()
	return s.synced
}

func (s *mockKubeconfigsSyncer) Sync(ctx context.Context, snap *KubeconfigsSnapshot) error {
	s.mutex.Lock()
	s.synced = true
	s.mutex.Unlock()
	return nil
}
