// Code generated by solo-kit. DO NOT EDIT.

package group

import (
	"sync"
	"time"

	github_com_solo_io_solo_kit_pkg_api_v1_resources_common_kubernetes "github.com/solo-io/solo-kit/pkg/api/v1/resources/common/kubernetes"
	github_com_solo_io_solo_kit_test_mocks_api_v1_customtype "github.com/solo-io/solo-kit/test/mocks/api/v1/customtype"
	testing_solo_io_kubernetes "github.com/solo-io/solo-kit/test/mocks/v1"

	"go.opencensus.io/stats"
	"go.opencensus.io/stats/view"
	"go.opencensus.io/tag"

	"github.com/solo-io/go-utils/errutils"
	"github.com/solo-io/solo-kit/pkg/api/v1/clients"
	"github.com/solo-io/solo-kit/pkg/errors"
)

var (
	mTestingSnapshotIn  = stats.Int64("testing.solo.io/snap_emitter/snap_in", "The number of snapshots in", "1")
	mTestingSnapshotOut = stats.Int64("testing.solo.io/snap_emitter/snap_out", "The number of snapshots out", "1")

	testingsnapshotInView = &view.View{
		Name:        "testing.solo.io_snap_emitter/snap_in",
		Measure:     mTestingSnapshotIn,
		Description: "The number of snapshots updates coming in",
		Aggregation: view.Count(),
		TagKeys:     []tag.Key{},
	}
	testingsnapshotOutView = &view.View{
		Name:        "testing.solo.io/snap_emitter/snap_out",
		Measure:     mTestingSnapshotOut,
		Description: "The number of snapshots updates going out",
		Aggregation: view.Count(),
		TagKeys:     []tag.Key{},
	}
)

func init() {
	view.Register(testingsnapshotInView, testingsnapshotOutView)
}

type TestingEmitter interface {
	Register() error
	MockResource() testing_solo_io_kubernetes.MockResourceClient
	FakeResource() testing_solo_io_kubernetes.FakeResourceClient
	AnotherMockResource() testing_solo_io_kubernetes.AnotherMockResourceClient
	ClusterResource() testing_solo_io_kubernetes.ClusterResourceClient
	MockCustomType() github_com_solo_io_solo_kit_test_mocks_api_v1_customtype.MockCustomTypeClient
	Pod() github_com_solo_io_solo_kit_pkg_api_v1_resources_common_kubernetes.PodClient
	Snapshots(watchNamespaces []string, opts clients.WatchOpts) (<-chan *TestingSnapshot, <-chan error, error)
}

func NewTestingEmitter(mockResourceClient testing_solo_io_kubernetes.MockResourceClient, fakeResourceClient testing_solo_io_kubernetes.FakeResourceClient, anotherMockResourceClient testing_solo_io_kubernetes.AnotherMockResourceClient, clusterResourceClient testing_solo_io_kubernetes.ClusterResourceClient, mockCustomTypeClient github_com_solo_io_solo_kit_test_mocks_api_v1_customtype.MockCustomTypeClient, podClient github_com_solo_io_solo_kit_pkg_api_v1_resources_common_kubernetes.PodClient) TestingEmitter {
	return NewTestingEmitterWithEmit(mockResourceClient, fakeResourceClient, anotherMockResourceClient, clusterResourceClient, mockCustomTypeClient, podClient, make(chan struct{}))
}

func NewTestingEmitterWithEmit(mockResourceClient testing_solo_io_kubernetes.MockResourceClient, fakeResourceClient testing_solo_io_kubernetes.FakeResourceClient, anotherMockResourceClient testing_solo_io_kubernetes.AnotherMockResourceClient, clusterResourceClient testing_solo_io_kubernetes.ClusterResourceClient, mockCustomTypeClient github_com_solo_io_solo_kit_test_mocks_api_v1_customtype.MockCustomTypeClient, podClient github_com_solo_io_solo_kit_pkg_api_v1_resources_common_kubernetes.PodClient, emit <-chan struct{}) TestingEmitter {
	return &testingEmitter{
		mockResource:        mockResourceClient,
		fakeResource:        fakeResourceClient,
		anotherMockResource: anotherMockResourceClient,
		clusterResource:     clusterResourceClient,
		mockCustomType:      mockCustomTypeClient,
		pod:                 podClient,
		forceEmit:           emit,
	}
}

type testingEmitter struct {
	forceEmit           <-chan struct{}
	mockResource        testing_solo_io_kubernetes.MockResourceClient
	fakeResource        testing_solo_io_kubernetes.FakeResourceClient
	anotherMockResource testing_solo_io_kubernetes.AnotherMockResourceClient
	clusterResource     testing_solo_io_kubernetes.ClusterResourceClient
	mockCustomType      github_com_solo_io_solo_kit_test_mocks_api_v1_customtype.MockCustomTypeClient
	pod                 github_com_solo_io_solo_kit_pkg_api_v1_resources_common_kubernetes.PodClient
}

func (c *testingEmitter) Register() error {
	if err := c.mockResource.Register(); err != nil {
		return err
	}
	if err := c.fakeResource.Register(); err != nil {
		return err
	}
	if err := c.anotherMockResource.Register(); err != nil {
		return err
	}
	if err := c.clusterResource.Register(); err != nil {
		return err
	}
	if err := c.mockCustomType.Register(); err != nil {
		return err
	}
	if err := c.pod.Register(); err != nil {
		return err
	}
	return nil
}

func (c *testingEmitter) MockResource() testing_solo_io_kubernetes.MockResourceClient {
	return c.mockResource
}

func (c *testingEmitter) FakeResource() testing_solo_io_kubernetes.FakeResourceClient {
	return c.fakeResource
}

func (c *testingEmitter) AnotherMockResource() testing_solo_io_kubernetes.AnotherMockResourceClient {
	return c.anotherMockResource
}

func (c *testingEmitter) ClusterResource() testing_solo_io_kubernetes.ClusterResourceClient {
	return c.clusterResource
}

func (c *testingEmitter) MockCustomType() github_com_solo_io_solo_kit_test_mocks_api_v1_customtype.MockCustomTypeClient {
	return c.mockCustomType
}

func (c *testingEmitter) Pod() github_com_solo_io_solo_kit_pkg_api_v1_resources_common_kubernetes.PodClient {
	return c.pod
}

func (c *testingEmitter) Snapshots(watchNamespaces []string, opts clients.WatchOpts) (<-chan *TestingSnapshot, <-chan error, error) {

	if len(watchNamespaces) == 0 {
		watchNamespaces = []string{""}
	}

	for _, ns := range watchNamespaces {
		if ns == "" && len(watchNamespaces) > 1 {
			return nil, nil, errors.Errorf("the \"\" namespace is used to watch all namespaces. Snapshots can either be tracked for " +
				"specific namespaces or \"\" AllNamespaces, but not both.")
		}
	}

	errs := make(chan error)
	var done sync.WaitGroup
	ctx := opts.Ctx
	/* Create channel for MockResource */
	type mockResourceListWithNamespace struct {
		list      testing_solo_io_kubernetes.MockResourceList
		namespace string
	}
	mockResourceChan := make(chan mockResourceListWithNamespace)
	/* Create channel for FakeResource */
	type fakeResourceListWithNamespace struct {
		list      testing_solo_io_kubernetes.FakeResourceList
		namespace string
	}
	fakeResourceChan := make(chan fakeResourceListWithNamespace)
	/* Create channel for AnotherMockResource */
	type anotherMockResourceListWithNamespace struct {
		list      testing_solo_io_kubernetes.AnotherMockResourceList
		namespace string
	}
	anotherMockResourceChan := make(chan anotherMockResourceListWithNamespace)
	/* Create channel for ClusterResource */
	/* Create channel for MockCustomType */
	type mockCustomTypeListWithNamespace struct {
		list      github_com_solo_io_solo_kit_test_mocks_api_v1_customtype.MockCustomTypeList
		namespace string
	}
	mockCustomTypeChan := make(chan mockCustomTypeListWithNamespace)
	/* Create channel for Pod */
	type podListWithNamespace struct {
		list      github_com_solo_io_solo_kit_pkg_api_v1_resources_common_kubernetes.PodList
		namespace string
	}
	podChan := make(chan podListWithNamespace)

	for _, namespace := range watchNamespaces {
		/* Setup namespaced watch for MockResource */
		mockResourceNamespacesChan, mockResourceErrs, err := c.mockResource.Watch(namespace, opts)
		if err != nil {
			return nil, nil, errors.Wrapf(err, "starting MockResource watch")
		}

		done.Add(1)
		go func(namespace string) {
			defer done.Done()
			errutils.AggregateErrs(ctx, errs, mockResourceErrs, namespace+"-mocks")
		}(namespace)
		/* Setup namespaced watch for FakeResource */
		fakeResourceNamespacesChan, fakeResourceErrs, err := c.fakeResource.Watch(namespace, opts)
		if err != nil {
			return nil, nil, errors.Wrapf(err, "starting FakeResource watch")
		}

		done.Add(1)
		go func(namespace string) {
			defer done.Done()
			errutils.AggregateErrs(ctx, errs, fakeResourceErrs, namespace+"-fakes")
		}(namespace)
		/* Setup namespaced watch for AnotherMockResource */
		anotherMockResourceNamespacesChan, anotherMockResourceErrs, err := c.anotherMockResource.Watch(namespace, opts)
		if err != nil {
			return nil, nil, errors.Wrapf(err, "starting AnotherMockResource watch")
		}

		done.Add(1)
		go func(namespace string) {
			defer done.Done()
			errutils.AggregateErrs(ctx, errs, anotherMockResourceErrs, namespace+"-anothermockresources")
		}(namespace)
		/* Setup namespaced watch for MockCustomType */
		mockCustomTypeNamespacesChan, mockCustomTypeErrs, err := c.mockCustomType.Watch(namespace, opts)
		if err != nil {
			return nil, nil, errors.Wrapf(err, "starting MockCustomType watch")
		}

		done.Add(1)
		go func(namespace string) {
			defer done.Done()
			errutils.AggregateErrs(ctx, errs, mockCustomTypeErrs, namespace+"-mcts")
		}(namespace)
		/* Setup namespaced watch for Pod */
		podNamespacesChan, podErrs, err := c.pod.Watch(namespace, opts)
		if err != nil {
			return nil, nil, errors.Wrapf(err, "starting Pod watch")
		}

		done.Add(1)
		go func(namespace string) {
			defer done.Done()
			errutils.AggregateErrs(ctx, errs, podErrs, namespace+"-pods")
		}(namespace)

		/* Watch for changes and update snapshot */
		go func(namespace string) {
			for {
				select {
				case <-ctx.Done():
					return
				case mockResourceList := <-mockResourceNamespacesChan:
					select {
					case <-ctx.Done():
						return
					case mockResourceChan <- mockResourceListWithNamespace{list: mockResourceList, namespace: namespace}:
					}
				case fakeResourceList := <-fakeResourceNamespacesChan:
					select {
					case <-ctx.Done():
						return
					case fakeResourceChan <- fakeResourceListWithNamespace{list: fakeResourceList, namespace: namespace}:
					}
				case anotherMockResourceList := <-anotherMockResourceNamespacesChan:
					select {
					case <-ctx.Done():
						return
					case anotherMockResourceChan <- anotherMockResourceListWithNamespace{list: anotherMockResourceList, namespace: namespace}:
					}
				case mockCustomTypeList := <-mockCustomTypeNamespacesChan:
					select {
					case <-ctx.Done():
						return
					case mockCustomTypeChan <- mockCustomTypeListWithNamespace{list: mockCustomTypeList, namespace: namespace}:
					}
				case podList := <-podNamespacesChan:
					select {
					case <-ctx.Done():
						return
					case podChan <- podListWithNamespace{list: podList, namespace: namespace}:
					}
				}
			}
		}(namespace)
	}
	/* Setup cluster-wide watch for ClusterResource */

	clusterResourceChan, clusterResourceErrs, err := c.clusterResource.Watch(opts)
	if err != nil {
		return nil, nil, errors.Wrapf(err, "starting ClusterResource watch")
	}
	done.Add(1)
	go func() {
		defer done.Done()
		errutils.AggregateErrs(ctx, errs, clusterResourceErrs, "clusterresources")
	}()

	snapshots := make(chan *TestingSnapshot)
	go func() {
		originalSnapshot := TestingSnapshot{}
		currentSnapshot := originalSnapshot.Clone()
		timer := time.NewTicker(time.Second * 1)
		sync := func() {
			if originalSnapshot.Hash() == currentSnapshot.Hash() {
				return
			}

			stats.Record(ctx, mTestingSnapshotOut.M(1))
			originalSnapshot = currentSnapshot.Clone()
			sentSnapshot := currentSnapshot.Clone()
			snapshots <- &sentSnapshot
		}
		mocksByNamespace := make(map[string]testing_solo_io_kubernetes.MockResourceList)
		fakesByNamespace := make(map[string]testing_solo_io_kubernetes.FakeResourceList)
		anothermockresourcesByNamespace := make(map[string]testing_solo_io_kubernetes.AnotherMockResourceList)
		mctsByNamespace := make(map[string]github_com_solo_io_solo_kit_test_mocks_api_v1_customtype.MockCustomTypeList)
		podsByNamespace := make(map[string]github_com_solo_io_solo_kit_pkg_api_v1_resources_common_kubernetes.PodList)

		for {
			record := func() { stats.Record(ctx, mTestingSnapshotIn.M(1)) }

			select {
			case <-timer.C:
				sync()
			case <-ctx.Done():
				close(snapshots)
				done.Wait()
				close(errs)
				return
			case <-c.forceEmit:
				sentSnapshot := currentSnapshot.Clone()
				snapshots <- &sentSnapshot
			case mockResourceNamespacedList := <-mockResourceChan:
				record()

				namespace := mockResourceNamespacedList.namespace

				// merge lists by namespace
				mocksByNamespace[namespace] = mockResourceNamespacedList.list
				var mockResourceList testing_solo_io_kubernetes.MockResourceList
				for _, mocks := range mocksByNamespace {
					mockResourceList = append(mockResourceList, mocks...)
				}
				currentSnapshot.Mocks = mockResourceList.Sort()
			case fakeResourceNamespacedList := <-fakeResourceChan:
				record()

				namespace := fakeResourceNamespacedList.namespace

				// merge lists by namespace
				fakesByNamespace[namespace] = fakeResourceNamespacedList.list
				var fakeResourceList testing_solo_io_kubernetes.FakeResourceList
				for _, fakes := range fakesByNamespace {
					fakeResourceList = append(fakeResourceList, fakes...)
				}
				currentSnapshot.Fakes = fakeResourceList.Sort()
			case anotherMockResourceNamespacedList := <-anotherMockResourceChan:
				record()

				namespace := anotherMockResourceNamespacedList.namespace

				// merge lists by namespace
				anothermockresourcesByNamespace[namespace] = anotherMockResourceNamespacedList.list
				var anotherMockResourceList testing_solo_io_kubernetes.AnotherMockResourceList
				for _, anothermockresources := range anothermockresourcesByNamespace {
					anotherMockResourceList = append(anotherMockResourceList, anothermockresources...)
				}
				currentSnapshot.Anothermockresources = anotherMockResourceList.Sort()
			case clusterResourceList := <-clusterResourceChan:
				record()
				currentSnapshot.Clusterresources = clusterResourceList
			case mockCustomTypeNamespacedList := <-mockCustomTypeChan:
				record()

				namespace := mockCustomTypeNamespacedList.namespace

				// merge lists by namespace
				mctsByNamespace[namespace] = mockCustomTypeNamespacedList.list
				var mockCustomTypeList github_com_solo_io_solo_kit_test_mocks_api_v1_customtype.MockCustomTypeList
				for _, mcts := range mctsByNamespace {
					mockCustomTypeList = append(mockCustomTypeList, mcts...)
				}
				currentSnapshot.Mcts = mockCustomTypeList.Sort()
			case podNamespacedList := <-podChan:
				record()

				namespace := podNamespacedList.namespace

				// merge lists by namespace
				podsByNamespace[namespace] = podNamespacedList.list
				var podList github_com_solo_io_solo_kit_pkg_api_v1_resources_common_kubernetes.PodList
				for _, pods := range podsByNamespace {
					podList = append(podList, pods...)
				}
				currentSnapshot.Pods = podList.Sort()
			}
		}
	}()
	return snapshots, errs, nil
}
