steps:
  # Using dep container from github.com/solo-io/cloud-builders/dep
  # This copies files into the proper workspace layout and so must be run before other tasks
  # Subsequent steps should set GOPATH variable to avoid setting up unnecessary sym link
  - name: 'gcr.io/$PROJECT_ID/dep'
    args: ['ensure', '-v']
    env: ['PROJECT_ROOT=github.com/solo-io/solo-kit']
    id: 'dep'

  # e2e-ginkgo is produced from https://github.com/solo-io/cloud-builders/e2e-ginkgo
  # sets up redis, consul, kubectl, go with required environment variables
  # need to use the provided entrypoint
  - name: 'gcr.io/$PROJECT_ID/e2e-ginkgo'
    dir: './gopath/src/github.com/solo-io/solo-kit'
    env:
      - 'PROJECT_ROOT=github.com/solo-io/solo-kit'
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=test-cluster'
      - 'RUN_KUBE_TESTS=1'
      - 'CLOUD_BUILD=1'
      - 'GOPATH=/workspace/gopath'
    args: ['-r', '-v', '-tags', 'solokit']
    id: 'test'
    waitFor: ['dep']

  - name: 'gcr.io/cloud-builders/go'
    args: ['build', '-o', 'solo-kit-gen', 'github.com/solo-io/solo-kit/cmd/cli']
    env:
      - 'PROJECT_ROOT=github.com/solo-io/solo-kit'
      - 'GOPATH=/workspace/gopath'
    id: 'build-cli'
    waitFor: ['test']

  - name: 'gcr.io/cloud-builders/go'
    args: ['build', '-o', 'solo-kit-cli', 'github.com/solo-io/solo-kit/cmd/solo-kit-gen']
    env:
      - 'PROJECT_ROOT=github.com/solo-io/solo-kit'
      - 'GOPATH=/workspace/gopath'
    id: 'build-codegen'
    waitFor: ['test']

timeout: 900s