steps:

- name: gcr.io/cloud-builders/gsutil
  entrypoint: 'bash'
  args: ['-c', 'mkdir -p /go/pkg && cd /go/pkg && gsutil cat gs://$PROJECT_ID-cache/solo-kit/solo-kit-mod.tar.gz | tar -xzf -']
  id: 'untar-mod-cache'
  dir: &dir '/workspace/solo-kit'

# prepare-workspace to set up the project so it can be built and tested
- name: 'gcr.io/$PROJECT_ID/prepare-go-workspace:0.4.28'
  args:
  - "--repo-name"
  - "$REPO_NAME"
  - "--repo-sha"
  - "$COMMIT_SHA"
  - "--repo-output-dir"
  - "."
  env:
  - 'GIT_SSH_CONFIG=FALSE'
  id: 'prepare-workspace'

# download massive container in parallel
- name: 'gcr.io/$PROJECT_ID/e2e-go-mod-ginkgo:0.4.28'
  entrypoint: 'bash'
  dir: *dir
  args: ['-c', 'ls']
  waitFor: ['-']

# Installs go executables required by codegen tests
- name: 'gcr.io/$PROJECT_ID/go-mod-make:0.4.28'
  args: ['update-all']
  waitFor: ['prepare-workspace']
  id: 'update-deps'
  dir: *dir

# Set gcloud Kubeconfig
- name: gcr.io/cloud-builders/gcloud
  args: ['config', 'set', 'compute/zone', 'us-central1-b']
  id: 'gcloud-compute-zone'
  dir: *dir

- name: gcr.io/cloud-builders/gcloud
  args: ['container', 'clusters', 'get-credentials', 'solo-kit-test']
  id: 'gcloud-solo-kit-test'

# e2e-go-mod-ginkgo is produced from https://github.com/solo-io/cloud-builders/tree/master/e2e-go-mod-ginkgo
# sets up redis, consul, kubectl, go with required environment variables
# need to use the provided entrypoint
- name: 'gcr.io/$PROJECT_ID/e2e-go-mod-ginkgo:0.4.28'
  entrypoint: 'bash'
  env:
  - 'RUN_KUBE_TESTS=1'
  - 'RUN_CONSUL_TESTS=1'
  - 'RUN_VAULT_TESTS=1'
  - 'TEST_PKG=./pkg/utils/...' # TODO: Run all tests
  args: ['-c', 'make test']
  waitFor: ['update-deps']
  dir: *dir
  id: 'test'

# check code gen for kubernetes custom resources
# this step passes if there is no generated diff, fails otherwise
- name: 'gcr.io/$PROJECT_ID/go-mod-make:0.4.28'
  entrypoint: 'bash'
  args: ['ci/check-code-gen.sh']
  waitFor: ['update-deps']
  dir: *dir
  id: 'check-code-and-docs-gen'

timeout: 1500s
tags: ['solo-kit']
options:
  machineType: 'N1_HIGHCPU_32'
  env:
    - 'TAGGED_VERSION=$TAG_NAME'
  volumes:
  - name: 'gopath'
    path: '/go'
