steps:
  # Can create a dep cache by running 'gcloud builds submit . --config=cloudbuild-cache.yaml'
  # These two steps should populate the cache
  - name: gcr.io/cloud-builders/gsutil
    entrypoint: 'bash'
    args: ['-c', 'mkdir -p ./gopath/pkg/dep && gsutil cat gs://solo-public-cache/solo-kit/solo-kit-dep.tar.gz | tar -xzf -']
    id: 'download-untar-dep-cache'
    waitFor: ['-']

  # Can create a dep cache by running 'gcloud builds submit . --config=cloudbuild-cache.yaml'
  # These two steps should populate the cache
  - name: gcr.io/cloud-builders/gsutil
    entrypoint: 'bash'
    args: ['-c', 'mkdir -p ./gopath/pkg/dep && gsutil cat gs://solo-public-cache/solo-kit/solo-kit-gocache.tar.gz | tar -xzf -']
    id: 'download-untar-go-cache'
    waitFor: ['-']

  # donwload massive container in parallel
  - name: 'gcr.io/$PROJECT_ID/e2e-ginkgo'
    entrypoint: 'bash'
    args: ['-c', 'ls']
    waitFor: ['-']

  # Run dep to set up the project so it can be built and tested
  # Dep modifies workspace so that the code is moved into the PROJECT_ROOT
  # All steps after this must set GOPATH
  - name: 'gcr.io/$PROJECT_ID/dep:0.1.5'
    args: ['ensure']
    env:
      - 'PROJECT_ROOT=github.com/solo-io/solo-kit'
      - 'GIT_SSH_CONFIG=FALSE'
    id: 'dep'
    waitFor: ['download-untar-dep-cache']


  # Installs go executables required by codegen tests
  - name: 'gcr.io/$PROJECT_ID/go-make:0.1.12'
    args: ['install-codegen-deps']
    waitFor: ['dep']
    dir: './gopath/src/github.com/solo-io/solo-kit'
    id: 'install-codegen-deps'
    env:
      - 'GOPATH=/workspace/gopath'

  # check code gen for kubernetes custom resources, should be no diff
  - name: 'gcr.io/$PROJECT_ID/go-make:0.1.12'
    entrypoint: 'bash'
    args: ['ci/check-code-gen.sh']
    env:
      - 'PROJECT_ROOT=github.com/solo-io/solo-kit'
      - 'GOPATH=/workspace/gopath'
      - 'TAGGED_VERSION=$TAG_NAME'
    dir: './gopath/src/github.com/solo-io/solo-kit'
    waitFor: ['install-codegen-deps']
    id: 'check-code-and-docs-gen'

    # start setting up kubeconfigs
  - name: gcr.io/cloud-builders/gcloud
    args: ['config', 'set', 'compute/zone', 'us-central1-b']
    id: 'gcloud-compute-zone'

  - name: gcr.io/cloud-builders/gcloud
    args: ['container', 'clusters', 'get-credentials', 'solo-kit-multicluster-2']
    id: 'gcloud-solo-kit-multicluster-2'

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: cp
    args:
      - /builder/home/.kube/config
      - /builder/home/.kube/solo-kit-multicluster-2-config
    id: 'copy-multicluster-2-config'

  - name: gcr.io/cloud-builders/gcloud
    args: ['container', 'clusters', 'get-credentials', 'solo-kit-test']
    id: 'gcloud-solo-kit-test'

  # e2e-ginkgo is produced from https://github.com/solo-io/cloud-builders/e2e-ginkgo
  # sets up redis, consul, kubectl, go with required environment variables
  # need to use the provided entrypoint
  - name: 'gcr.io/$PROJECT_ID/e2e-ginkgo'
    dir: './gopath/src/github.com/solo-io/solo-kit'
    env:
      - 'PROJECT_ROOT=github.com/solo-io/solo-kit'
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=solo-kit-test'
      - 'RUN_KUBE_TESTS=1'
      - 'RUN_CONSUL_TESTS=1'
      - 'RUN_VAULT_TESTS=1'
      - 'SKIP_MOCK_GEN=1'
      - 'CLOUD_BUILD=1'
      - 'GOPATH=/workspace/gopath'
      - 'ALT_CLUSTER_KUBECONFIG=/builder/home/.kube/solo-kit-multicluster-2-config'
    args: ['-r', '-v', '-race', '-p', '-tags', 'solokit']
    id: 'test'

  - name: 'gcr.io/cloud-builders/go'
    args: ['build', '-o', 'solo-kit-gen', 'github.com/solo-io/solo-kit/cmd/cli']
    env:
      - 'PROJECT_ROOT=github.com/solo-io/solo-kit'
      - 'GOPATH=/workspace/gopath'
    id: 'build-cli'
    waitFor: ['test']

  - name: 'gcr.io/cloud-builders/go'
    args: ['build', '-o', 'solo-kit-cli', 'github.com/solo-io/solo-kit/cmd/solo-kit-gen']
    env:
      - 'PROJECT_ROOT=github.com/solo-io/solo-kit'
      - 'GOPATH=/workspace/gopath'
    id: 'build-codegen'
    waitFor: ['test']

timeout: 1500s
tags: ['solo-kit']
options:
  machineType: 'N1_HIGHCPU_32'