// Code generated by MockGen. DO NOT EDIT.
// Source: test/mocks/v2alpha1/frequently_changing_annotations_resource_client.sk.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	clients "github.com/solo-io/solo-kit/pkg/api/v1/clients"
	v2alpha1 "github.com/solo-io/solo-kit/test/mocks/v2alpha1"
)

// MockFrequentlyChangingAnnotationsResourceWatcher is a mock of FrequentlyChangingAnnotationsResourceWatcher interface
type MockFrequentlyChangingAnnotationsResourceWatcher struct {
	ctrl     *gomock.Controller
	recorder *MockFrequentlyChangingAnnotationsResourceWatcherMockRecorder
}

// MockFrequentlyChangingAnnotationsResourceWatcherMockRecorder is the mock recorder for MockFrequentlyChangingAnnotationsResourceWatcher
type MockFrequentlyChangingAnnotationsResourceWatcherMockRecorder struct {
	mock *MockFrequentlyChangingAnnotationsResourceWatcher
}

// NewMockFrequentlyChangingAnnotationsResourceWatcher creates a new mock instance
func NewMockFrequentlyChangingAnnotationsResourceWatcher(ctrl *gomock.Controller) *MockFrequentlyChangingAnnotationsResourceWatcher {
	mock := &MockFrequentlyChangingAnnotationsResourceWatcher{ctrl: ctrl}
	mock.recorder = &MockFrequentlyChangingAnnotationsResourceWatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFrequentlyChangingAnnotationsResourceWatcher) EXPECT() *MockFrequentlyChangingAnnotationsResourceWatcherMockRecorder {
	return m.recorder
}

// Watch mocks base method
func (m *MockFrequentlyChangingAnnotationsResourceWatcher) Watch(namespace string, opts clients.WatchOpts) (<-chan v2alpha1.FrequentlyChangingAnnotationsResourceList, <-chan error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", namespace, opts)
	ret0, _ := ret[0].(<-chan v2alpha1.FrequentlyChangingAnnotationsResourceList)
	ret1, _ := ret[1].(<-chan error)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Watch indicates an expected call of Watch
func (mr *MockFrequentlyChangingAnnotationsResourceWatcherMockRecorder) Watch(namespace, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockFrequentlyChangingAnnotationsResourceWatcher)(nil).Watch), namespace, opts)
}

// MockFrequentlyChangingAnnotationsResourceClient is a mock of FrequentlyChangingAnnotationsResourceClient interface
type MockFrequentlyChangingAnnotationsResourceClient struct {
	ctrl     *gomock.Controller
	recorder *MockFrequentlyChangingAnnotationsResourceClientMockRecorder
}

// MockFrequentlyChangingAnnotationsResourceClientMockRecorder is the mock recorder for MockFrequentlyChangingAnnotationsResourceClient
type MockFrequentlyChangingAnnotationsResourceClientMockRecorder struct {
	mock *MockFrequentlyChangingAnnotationsResourceClient
}

// NewMockFrequentlyChangingAnnotationsResourceClient creates a new mock instance
func NewMockFrequentlyChangingAnnotationsResourceClient(ctrl *gomock.Controller) *MockFrequentlyChangingAnnotationsResourceClient {
	mock := &MockFrequentlyChangingAnnotationsResourceClient{ctrl: ctrl}
	mock.recorder = &MockFrequentlyChangingAnnotationsResourceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFrequentlyChangingAnnotationsResourceClient) EXPECT() *MockFrequentlyChangingAnnotationsResourceClientMockRecorder {
	return m.recorder
}

// BaseClient mocks base method
func (m *MockFrequentlyChangingAnnotationsResourceClient) BaseClient() clients.ResourceClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BaseClient")
	ret0, _ := ret[0].(clients.ResourceClient)
	return ret0
}

// BaseClient indicates an expected call of BaseClient
func (mr *MockFrequentlyChangingAnnotationsResourceClientMockRecorder) BaseClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BaseClient", reflect.TypeOf((*MockFrequentlyChangingAnnotationsResourceClient)(nil).BaseClient))
}

// Register mocks base method
func (m *MockFrequentlyChangingAnnotationsResourceClient) Register() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register")
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register
func (mr *MockFrequentlyChangingAnnotationsResourceClientMockRecorder) Register() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockFrequentlyChangingAnnotationsResourceClient)(nil).Register))
}

// Read mocks base method
func (m *MockFrequentlyChangingAnnotationsResourceClient) Read(namespace, name string, opts clients.ReadOpts) (*v2alpha1.FrequentlyChangingAnnotationsResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", namespace, name, opts)
	ret0, _ := ret[0].(*v2alpha1.FrequentlyChangingAnnotationsResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read
func (mr *MockFrequentlyChangingAnnotationsResourceClientMockRecorder) Read(namespace, name, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockFrequentlyChangingAnnotationsResourceClient)(nil).Read), namespace, name, opts)
}

// Write mocks base method
func (m *MockFrequentlyChangingAnnotationsResourceClient) Write(resource *v2alpha1.FrequentlyChangingAnnotationsResource, opts clients.WriteOpts) (*v2alpha1.FrequentlyChangingAnnotationsResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", resource, opts)
	ret0, _ := ret[0].(*v2alpha1.FrequentlyChangingAnnotationsResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write
func (mr *MockFrequentlyChangingAnnotationsResourceClientMockRecorder) Write(resource, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockFrequentlyChangingAnnotationsResourceClient)(nil).Write), resource, opts)
}

// Delete mocks base method
func (m *MockFrequentlyChangingAnnotationsResourceClient) Delete(namespace, name string, opts clients.DeleteOpts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", namespace, name, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockFrequentlyChangingAnnotationsResourceClientMockRecorder) Delete(namespace, name, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFrequentlyChangingAnnotationsResourceClient)(nil).Delete), namespace, name, opts)
}

// List mocks base method
func (m *MockFrequentlyChangingAnnotationsResourceClient) List(namespace string, opts clients.ListOpts) (v2alpha1.FrequentlyChangingAnnotationsResourceList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", namespace, opts)
	ret0, _ := ret[0].(v2alpha1.FrequentlyChangingAnnotationsResourceList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockFrequentlyChangingAnnotationsResourceClientMockRecorder) List(namespace, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFrequentlyChangingAnnotationsResourceClient)(nil).List), namespace, opts)
}

// Watch mocks base method
func (m *MockFrequentlyChangingAnnotationsResourceClient) Watch(namespace string, opts clients.WatchOpts) (<-chan v2alpha1.FrequentlyChangingAnnotationsResourceList, <-chan error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", namespace, opts)
	ret0, _ := ret[0].(<-chan v2alpha1.FrequentlyChangingAnnotationsResourceList)
	ret1, _ := ret[1].(<-chan error)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Watch indicates an expected call of Watch
func (mr *MockFrequentlyChangingAnnotationsResourceClientMockRecorder) Watch(namespace, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockFrequentlyChangingAnnotationsResourceClient)(nil).Watch), namespace, opts)
}
