// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mock_resources.proto

package v1 // import "github.com/solo-io/solo-kit/test/mocks/v1"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import core "github.com/solo-io/solo-kit/pkg/api/v1/resources/core"

import bytes "bytes"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

//
// @solo-kit:resource.short_name=mk
// @solo-kit:resource.plural_name=mocks
// @solo-kit:resource.resource_groups=testing.solo.io
type MockResource struct {
	Data                 string        `protobuf:"bytes,1,opt,name=data,json=data.json,proto3" json:"data.json"`
	Status               core.Status   `protobuf:"bytes,6,opt,name=status" json:"status"`
	Metadata             core.Metadata `protobuf:"bytes,7,opt,name=metadata" json:"metadata"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MockResource) Reset()         { *m = MockResource{} }
func (m *MockResource) String() string { return proto.CompactTextString(m) }
func (*MockResource) ProtoMessage()    {}
func (*MockResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_mock_resources_53046872aed7bdaa, []int{0}
}
func (m *MockResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MockResource.Unmarshal(m, b)
}
func (m *MockResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MockResource.Marshal(b, m, deterministic)
}
func (dst *MockResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MockResource.Merge(dst, src)
}
func (m *MockResource) XXX_Size() int {
	return xxx_messageInfo_MockResource.Size(m)
}
func (m *MockResource) XXX_DiscardUnknown() {
	xxx_messageInfo_MockResource.DiscardUnknown(m)
}

var xxx_messageInfo_MockResource proto.InternalMessageInfo

func (m *MockResource) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *MockResource) GetStatus() core.Status {
	if m != nil {
		return m.Status
	}
	return core.Status{}
}

func (m *MockResource) GetMetadata() core.Metadata {
	if m != nil {
		return m.Metadata
	}
	return core.Metadata{}
}

//
// @solo-kit:resource.short_name=fk
// @solo-kit:resource.plural_name=fakes
// @solo-kit:resource.resource_groups=testing.solo.io
type FakeResource struct {
	Count                uint32        `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Metadata             core.Metadata `protobuf:"bytes,7,opt,name=metadata" json:"metadata"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FakeResource) Reset()         { *m = FakeResource{} }
func (m *FakeResource) String() string { return proto.CompactTextString(m) }
func (*FakeResource) ProtoMessage()    {}
func (*FakeResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_mock_resources_53046872aed7bdaa, []int{1}
}
func (m *FakeResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FakeResource.Unmarshal(m, b)
}
func (m *FakeResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FakeResource.Marshal(b, m, deterministic)
}
func (dst *FakeResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FakeResource.Merge(dst, src)
}
func (m *FakeResource) XXX_Size() int {
	return xxx_messageInfo_FakeResource.Size(m)
}
func (m *FakeResource) XXX_DiscardUnknown() {
	xxx_messageInfo_FakeResource.DiscardUnknown(m)
}

var xxx_messageInfo_FakeResource proto.InternalMessageInfo

func (m *FakeResource) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *FakeResource) GetMetadata() core.Metadata {
	if m != nil {
		return m.Metadata
	}
	return core.Metadata{}
}

func init() {
	proto.RegisterType((*MockResource)(nil), "testing.solo.io.MockResource")
	proto.RegisterType((*FakeResource)(nil), "testing.solo.io.FakeResource")
}
func (this *MockResource) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MockResource)
	if !ok {
		that2, ok := that.(MockResource)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Data != that1.Data {
		return false
	}
	if !this.Status.Equal(&that1.Status) {
		return false
	}
	if !this.Metadata.Equal(&that1.Metadata) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *FakeResource) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FakeResource)
	if !ok {
		that2, ok := that.(FakeResource)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Count != that1.Count {
		return false
	}
	if !this.Metadata.Equal(&that1.Metadata) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}

func init() {
	proto.RegisterFile("mock_resources.proto", fileDescriptor_mock_resources_53046872aed7bdaa)
}

var fileDescriptor_mock_resources_53046872aed7bdaa = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc9, 0xcd, 0x4f, 0xce,
	0x8e, 0x2f, 0x4a, 0x2d, 0xce, 0x2f, 0x2d, 0x4a, 0x4e, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x2f, 0x49, 0x2d, 0x2e, 0xc9, 0xcc, 0x4b, 0xd7, 0x2b, 0xce, 0xcf, 0xc9, 0xd7, 0xcb,
	0xcc, 0x97, 0x12, 0x49, 0xcf, 0x4f, 0xcf, 0x07, 0xcb, 0xe9, 0x83, 0x58, 0x10, 0x65, 0x52, 0x86,
	0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0x20, 0x95, 0xba, 0x99, 0xf9,
	0x10, 0x3a, 0x3b, 0xb3, 0x44, 0x3f, 0xb1, 0x20, 0x53, 0xbf, 0xcc, 0x50, 0x3f, 0x37, 0xb5, 0x24,
	0x31, 0x25, 0xb1, 0x24, 0x11, 0xaa, 0x45, 0x9f, 0x08, 0x2d, 0xc5, 0x25, 0x89, 0x25, 0xa5, 0x50,
	0xa7, 0x28, 0x2d, 0x61, 0xe4, 0xe2, 0xf1, 0xcd, 0x4f, 0xce, 0x0e, 0x82, 0x3a, 0x51, 0x48, 0x8d,
	0x8b, 0x05, 0x64, 0x9e, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0xa7, 0x13, 0xef, 0xab, 0x7b, 0xf2, 0x9c,
	0x60, 0xf3, 0xb3, 0x8a, 0xf3, 0xf3, 0x82, 0x10, 0x4c, 0x21, 0x23, 0x2e, 0x36, 0x88, 0x41, 0x12,
	0x6c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0x22, 0x7a, 0xc9, 0xf9, 0x45, 0xa9, 0x30, 0x1f, 0xe9, 0x05,
	0x83, 0xe5, 0x9c, 0x58, 0x4e, 0xdc, 0x93, 0x67, 0x08, 0x82, 0xaa, 0x14, 0xb2, 0xe0, 0xe2, 0x80,
	0xb9, 0x57, 0x82, 0x1d, 0xac, 0x4b, 0x0c, 0x55, 0x97, 0x2f, 0x54, 0x16, 0xaa, 0x0f, 0xae, 0x5a,
	0x29, 0x8e, 0x8b, 0xc7, 0x2d, 0x31, 0x3b, 0x15, 0xee, 0x4a, 0x11, 0x2e, 0xd6, 0xe4, 0xfc, 0xd2,
	0xbc, 0x12, 0xb0, 0x33, 0x79, 0x83, 0x20, 0x1c, 0xf2, 0xcd, 0x77, 0xd2, 0x5f, 0xf1, 0x48, 0x8e,
	0x31, 0x4a, 0x13, 0x5f, 0xe8, 0x81, 0xe2, 0x4c, 0x1f, 0x14, 0x9d, 0xc5, 0xfa, 0x65, 0x86, 0x49,
	0x6c, 0xe0, 0xe0, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xf7, 0xe8, 0x7b, 0x91, 0xe1, 0x01,
	0x00, 0x00,
}
