// Code generated by solo-kit. DO NOT EDIT.

package v1

import (
	"github.com/solo-io/solo-kit/pkg/api/v1/resources"
	"github.com/solo-io/solo-kit/pkg/utils/hashutils"
	"go.uber.org/zap"
)

type TestingSnapshot struct {
	Mocks MocksByNamespace
	Fakes FakesByNamespace
}

func (s TestingSnapshot) Clone() TestingSnapshot {
	return TestingSnapshot{
		Mocks: s.Mocks.Clone(),
		Fakes: s.Fakes.Clone(),
	}
}

func (s TestingSnapshot) Hash() uint64 {
	return hashutils.HashAll(
		s.hashMocks(),
		s.hashFakes(),
	)
}

func (s TestingSnapshot) hashMocks() uint64 {
	var hashes []uint64
	for _, res := range s.Mocks.List() {
		hashes = append(hashes, resources.HashResource(res))
	}
	return hashutils.HashAll(hashes)
}

func (s TestingSnapshot) hashFakes() uint64 {
	var hashes []uint64
	for _, res := range s.Fakes.List() {
		hashes = append(hashes, resources.HashResource(res))
	}
	return hashutils.HashAll(hashes)
}

func (s TestingSnapshot) HashFields() []zap.Field {
	var fields []zap.Field
	fields = append(fields, zap.Uint64("mocks", s.hashMocks()))
	fields = append(fields, zap.Uint64("fakes", s.hashFakes()))

	return append(fields, zap.Uint64("snapshotHash", s.Hash()))
}
