// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/eitanya/go/src/github.com/solo-io/solo-kit/test/mocks/v1/cluster_resource.sk.go

// Package mocks is a generated GoMock package.
package mocks
