// Code generated by MockGen. DO NOT EDIT.
// Source: ./test/mocks/v1/mock_resource_reconciler.sk.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	clients "github.com/solo-io/solo-kit/pkg/api/v1/clients"
	v1 "github.com/solo-io/solo-kit/test/mocks/v1"
)

// MockMockResourceReconciler is a mock of MockResourceReconciler interface
type MockMockResourceReconciler struct {
	ctrl     *gomock.Controller
	recorder *MockMockResourceReconcilerMockRecorder
}

// MockMockResourceReconcilerMockRecorder is the mock recorder for MockMockResourceReconciler
type MockMockResourceReconcilerMockRecorder struct {
	mock *MockMockResourceReconciler
}

// NewMockMockResourceReconciler creates a new mock instance
func NewMockMockResourceReconciler(ctrl *gomock.Controller) *MockMockResourceReconciler {
	mock := &MockMockResourceReconciler{ctrl: ctrl}
	mock.recorder = &MockMockResourceReconcilerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMockResourceReconciler) EXPECT() *MockMockResourceReconcilerMockRecorder {
	return m.recorder
}

// Reconcile mocks base method
func (m *MockMockResourceReconciler) Reconcile(namespace string, desiredResources v1.MockResourceList, transition v1.TransitionMockResourceFunc, opts clients.ListOpts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reconcile", namespace, desiredResources, transition, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reconcile indicates an expected call of Reconcile
func (mr *MockMockResourceReconcilerMockRecorder) Reconcile(namespace, desiredResources, transition, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconcile", reflect.TypeOf((*MockMockResourceReconciler)(nil).Reconcile), namespace, desiredResources, transition, opts)
}
