// Code generated by MockGen. DO NOT EDIT.
// Source: test/mocks/v1/mock_custom_spec_hash_type_client.sk.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	clients "github.com/solo-io/solo-kit/pkg/api/v1/clients"
	v1 "github.com/solo-io/solo-kit/test/mocks/v1"
)

// MockMockCustomSpecHashTypeWatcher is a mock of MockCustomSpecHashTypeWatcher interface
type MockMockCustomSpecHashTypeWatcher struct {
	ctrl     *gomock.Controller
	recorder *MockMockCustomSpecHashTypeWatcherMockRecorder
}

// MockMockCustomSpecHashTypeWatcherMockRecorder is the mock recorder for MockMockCustomSpecHashTypeWatcher
type MockMockCustomSpecHashTypeWatcherMockRecorder struct {
	mock *MockMockCustomSpecHashTypeWatcher
}

// NewMockMockCustomSpecHashTypeWatcher creates a new mock instance
func NewMockMockCustomSpecHashTypeWatcher(ctrl *gomock.Controller) *MockMockCustomSpecHashTypeWatcher {
	mock := &MockMockCustomSpecHashTypeWatcher{ctrl: ctrl}
	mock.recorder = &MockMockCustomSpecHashTypeWatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMockCustomSpecHashTypeWatcher) EXPECT() *MockMockCustomSpecHashTypeWatcherMockRecorder {
	return m.recorder
}

// Watch mocks base method
func (m *MockMockCustomSpecHashTypeWatcher) Watch(namespace string, opts clients.WatchOpts) (<-chan v1.MockCustomSpecHashTypeList, <-chan error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", namespace, opts)
	ret0, _ := ret[0].(<-chan v1.MockCustomSpecHashTypeList)
	ret1, _ := ret[1].(<-chan error)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Watch indicates an expected call of Watch
func (mr *MockMockCustomSpecHashTypeWatcherMockRecorder) Watch(namespace, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockMockCustomSpecHashTypeWatcher)(nil).Watch), namespace, opts)
}

// MockMockCustomSpecHashTypeClient is a mock of MockCustomSpecHashTypeClient interface
type MockMockCustomSpecHashTypeClient struct {
	ctrl     *gomock.Controller
	recorder *MockMockCustomSpecHashTypeClientMockRecorder
}

// MockMockCustomSpecHashTypeClientMockRecorder is the mock recorder for MockMockCustomSpecHashTypeClient
type MockMockCustomSpecHashTypeClientMockRecorder struct {
	mock *MockMockCustomSpecHashTypeClient
}

// NewMockMockCustomSpecHashTypeClient creates a new mock instance
func NewMockMockCustomSpecHashTypeClient(ctrl *gomock.Controller) *MockMockCustomSpecHashTypeClient {
	mock := &MockMockCustomSpecHashTypeClient{ctrl: ctrl}
	mock.recorder = &MockMockCustomSpecHashTypeClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMockCustomSpecHashTypeClient) EXPECT() *MockMockCustomSpecHashTypeClientMockRecorder {
	return m.recorder
}

// BaseClient mocks base method
func (m *MockMockCustomSpecHashTypeClient) BaseClient() clients.ResourceClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BaseClient")
	ret0, _ := ret[0].(clients.ResourceClient)
	return ret0
}

// BaseClient indicates an expected call of BaseClient
func (mr *MockMockCustomSpecHashTypeClientMockRecorder) BaseClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BaseClient", reflect.TypeOf((*MockMockCustomSpecHashTypeClient)(nil).BaseClient))
}

// Register mocks base method
func (m *MockMockCustomSpecHashTypeClient) Register() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register")
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register
func (mr *MockMockCustomSpecHashTypeClientMockRecorder) Register() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockMockCustomSpecHashTypeClient)(nil).Register))
}

// Read mocks base method
func (m *MockMockCustomSpecHashTypeClient) Read(namespace, name string, opts clients.ReadOpts) (*v1.MockCustomSpecHashType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", namespace, name, opts)
	ret0, _ := ret[0].(*v1.MockCustomSpecHashType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read
func (mr *MockMockCustomSpecHashTypeClientMockRecorder) Read(namespace, name, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockMockCustomSpecHashTypeClient)(nil).Read), namespace, name, opts)
}

// Write mocks base method
func (m *MockMockCustomSpecHashTypeClient) Write(resource *v1.MockCustomSpecHashType, opts clients.WriteOpts) (*v1.MockCustomSpecHashType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", resource, opts)
	ret0, _ := ret[0].(*v1.MockCustomSpecHashType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write
func (mr *MockMockCustomSpecHashTypeClientMockRecorder) Write(resource, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockMockCustomSpecHashTypeClient)(nil).Write), resource, opts)
}

// Delete mocks base method
func (m *MockMockCustomSpecHashTypeClient) Delete(namespace, name string, opts clients.DeleteOpts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", namespace, name, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockMockCustomSpecHashTypeClientMockRecorder) Delete(namespace, name, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMockCustomSpecHashTypeClient)(nil).Delete), namespace, name, opts)
}

// List mocks base method
func (m *MockMockCustomSpecHashTypeClient) List(namespace string, opts clients.ListOpts) (v1.MockCustomSpecHashTypeList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", namespace, opts)
	ret0, _ := ret[0].(v1.MockCustomSpecHashTypeList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockMockCustomSpecHashTypeClientMockRecorder) List(namespace, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMockCustomSpecHashTypeClient)(nil).List), namespace, opts)
}

// Watch mocks base method
func (m *MockMockCustomSpecHashTypeClient) Watch(namespace string, opts clients.WatchOpts) (<-chan v1.MockCustomSpecHashTypeList, <-chan error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", namespace, opts)
	ret0, _ := ret[0].(<-chan v1.MockCustomSpecHashTypeList)
	ret1, _ := ret[1].(<-chan error)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Watch indicates an expected call of Watch
func (mr *MockMockCustomSpecHashTypeClientMockRecorder) Watch(namespace, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockMockCustomSpecHashTypeClient)(nil).Watch), namespace, opts)
}
