// Code generated by solo-kit. DO NOT EDIT.

package kubernetes

import (
	"testing"

	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

func TestKubernetessoloio(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "Kubernetessoloio Suite")
}
