changelog:
  - type: DEPENDENCY_BUMP
    dependencyOwner: solo-io
    dependencyRepo: protoc-gen-openapi
    dependencyTag: v0.0.5
  - type: FIX
    description: Support injecting a set of message names to generate empty validation schema
    issueLink: https://github.com/solo-io/gloo/issues/4789
    resolvesIssue: false