// Code template generated by solo-kit. Feel free to Edit.


package options


type Options struct {
	Name string
	Config Config
	MockResource MockResource
	FakeResource FakeResource
	
}

type Config struct {
}

type MockResource struct {
}
type FakeResource struct {
}



