// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ref.proto

package core

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "github.com/solo-io/protoc-gen-ext/extproto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// A way to reference resources across namespaces
type ResourceRef struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceRef) Reset()         { *m = ResourceRef{} }
func (m *ResourceRef) String() string { return proto.CompactTextString(m) }
func (*ResourceRef) ProtoMessage()    {}
func (*ResourceRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_65d958559ea81b29, []int{0}
}
func (m *ResourceRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceRef.Unmarshal(m, b)
}
func (m *ResourceRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceRef.Marshal(b, m, deterministic)
}
func (m *ResourceRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceRef.Merge(m, src)
}
func (m *ResourceRef) XXX_Size() int {
	return xxx_messageInfo_ResourceRef.Size(m)
}
func (m *ResourceRef) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceRef.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceRef proto.InternalMessageInfo

func (m *ResourceRef) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResourceRef) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func init() {
	proto.RegisterType((*ResourceRef)(nil), "core.solo.io.ResourceRef")
}

func init() { proto.RegisterFile("ref.proto", fileDescriptor_65d958559ea81b29) }

var fileDescriptor_65d958559ea81b29 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0x4a, 0x4d, 0xd3,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x49, 0xce, 0x2f, 0x4a, 0xd5, 0x2b, 0xce, 0xcf, 0xc9,
	0xd7, 0xcb, 0xcc, 0x97, 0x12, 0x4a, 0xad, 0x28, 0x01, 0x8b, 0xeb, 0xa7, 0x56, 0x94, 0x40, 0x54,
	0x28, 0xd9, 0x73, 0x71, 0x07, 0xa5, 0x16, 0xe7, 0x97, 0x16, 0x25, 0xa7, 0x06, 0xa5, 0xa6, 0x09,
	0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9,
	0x42, 0x32, 0x5c, 0x9c, 0x20, 0xba, 0xb8, 0x20, 0x31, 0x39, 0x55, 0x82, 0x09, 0x2c, 0x81, 0x10,
	0x70, 0xb2, 0xdf, 0xf1, 0x95, 0x85, 0xf1, 0xc0, 0x57, 0x16, 0xc6, 0x28, 0xd3, 0xf4, 0xcc, 0x92,
	0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0x7d, 0x90, 0x95, 0xba, 0x99, 0xf9, 0x10, 0x3a, 0x3b,
	0xb3, 0x44, 0xbf, 0x20, 0x3b, 0x5d, 0x3f, 0xb1, 0x20, 0x53, 0xbf, 0xcc, 0x50, 0xbf, 0x08, 0x6a,
	0x5f, 0xb1, 0x3e, 0xc8, 0x75, 0x49, 0x6c, 0x60, 0x87, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x0f, 0x55, 0xc9, 0x5a, 0xb7, 0x00, 0x00, 0x00,
}
