// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: test/mocks/api/v1alpha1/mock_resources.proto

//
//package Comments
//package Comments a

package v1alpha1

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/envoyproxy/go-control-plane/envoy/api/v2"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/solo-io/protoc-gen-ext/extproto"
	core "github.com/solo-io/solo-kit/pkg/api/v1/resources/core"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//
//Mock resources for goofin off
type MockResource struct {
	Status        core.Status   `protobuf:"bytes,6,opt,name=status,proto3" json:"status"`
	Metadata      core.Metadata `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata"`
	Data          string        `protobuf:"bytes,1,opt,name=data,json=data.json,proto3" json:"data.json"`
	SomeDumbField string        `protobuf:"bytes,100,opt,name=some_dumb_field,json=someDumbField,proto3" json:"some_dumb_field,omitempty"`
	// Types that are valid to be assigned to TestOneofFields:
	//	*MockResource_OneofOne
	//	*MockResource_OneofTwo
	TestOneofFields      isMockResource_TestOneofFields `protobuf_oneof:"test_oneof_fields"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *MockResource) Reset()         { *m = MockResource{} }
func (m *MockResource) String() string { return proto.CompactTextString(m) }
func (*MockResource) ProtoMessage()    {}
func (*MockResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b69b55b4c8a991d, []int{0}
}
func (m *MockResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MockResource.Unmarshal(m, b)
}
func (m *MockResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MockResource.Marshal(b, m, deterministic)
}
func (m *MockResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MockResource.Merge(m, src)
}
func (m *MockResource) XXX_Size() int {
	return xxx_messageInfo_MockResource.Size(m)
}
func (m *MockResource) XXX_DiscardUnknown() {
	xxx_messageInfo_MockResource.DiscardUnknown(m)
}

var xxx_messageInfo_MockResource proto.InternalMessageInfo

type isMockResource_TestOneofFields interface {
	isMockResource_TestOneofFields()
	Equal(interface{}) bool
}

type MockResource_OneofOne struct {
	OneofOne string `protobuf:"bytes,3,opt,name=oneof_one,json=oneofOne,proto3,oneof" json:"oneof_one,omitempty"`
}
type MockResource_OneofTwo struct {
	OneofTwo bool `protobuf:"varint,2,opt,name=oneof_two,json=oneofTwo,proto3,oneof" json:"oneof_two,omitempty"`
}

func (*MockResource_OneofOne) isMockResource_TestOneofFields() {}
func (*MockResource_OneofTwo) isMockResource_TestOneofFields() {}

func (m *MockResource) GetTestOneofFields() isMockResource_TestOneofFields {
	if m != nil {
		return m.TestOneofFields
	}
	return nil
}

func (m *MockResource) GetStatus() core.Status {
	if m != nil {
		return m.Status
	}
	return core.Status{}
}

func (m *MockResource) GetMetadata() core.Metadata {
	if m != nil {
		return m.Metadata
	}
	return core.Metadata{}
}

func (m *MockResource) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *MockResource) GetSomeDumbField() string {
	if m != nil {
		return m.SomeDumbField
	}
	return ""
}

func (m *MockResource) GetOneofOne() string {
	if x, ok := m.GetTestOneofFields().(*MockResource_OneofOne); ok {
		return x.OneofOne
	}
	return ""
}

func (m *MockResource) GetOneofTwo() bool {
	if x, ok := m.GetTestOneofFields().(*MockResource_OneofTwo); ok {
		return x.OneofTwo
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MockResource) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MockResource_OneofOne)(nil),
		(*MockResource_OneofTwo)(nil),
	}
}

type FakeResource struct {
	Count                uint32        `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Metadata             core.Metadata `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FakeResource) Reset()         { *m = FakeResource{} }
func (m *FakeResource) String() string { return proto.CompactTextString(m) }
func (*FakeResource) ProtoMessage()    {}
func (*FakeResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b69b55b4c8a991d, []int{1}
}
func (m *FakeResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FakeResource.Unmarshal(m, b)
}
func (m *FakeResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FakeResource.Marshal(b, m, deterministic)
}
func (m *FakeResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FakeResource.Merge(m, src)
}
func (m *FakeResource) XXX_Size() int {
	return xxx_messageInfo_FakeResource.Size(m)
}
func (m *FakeResource) XXX_DiscardUnknown() {
	xxx_messageInfo_FakeResource.DiscardUnknown(m)
}

var xxx_messageInfo_FakeResource proto.InternalMessageInfo

func (m *FakeResource) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *FakeResource) GetMetadata() core.Metadata {
	if m != nil {
		return m.Metadata
	}
	return core.Metadata{}
}

func init() {
	proto.RegisterType((*MockResource)(nil), "testing.solo.io.MockResource")
	proto.RegisterType((*FakeResource)(nil), "testing.solo.io.FakeResource")
}

func init() {
	proto.RegisterFile("test/mocks/api/v1alpha1/mock_resources.proto", fileDescriptor_6b69b55b4c8a991d)
}

var fileDescriptor_6b69b55b4c8a991d = []byte{
	// 448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0x5f, 0xba, 0xac, 0x7f, 0xcc, 0xaa, 0x89, 0xac, 0x42, 0x51, 0x35, 0xb6, 0x6a, 0x07, 0x54,
	0x09, 0x88, 0xb5, 0x21, 0xa4, 0x89, 0xa3, 0x85, 0x26, 0x2e, 0x13, 0x52, 0xe0, 0xc4, 0x25, 0x72,
	0x93, 0xd7, 0xcc, 0xa4, 0xf1, 0xab, 0x62, 0xa7, 0xdb, 0xae, 0xfb, 0x34, 0x7c, 0x08, 0x3e, 0x00,
	0x9f, 0x62, 0x07, 0x8e, 0xdc, 0x76, 0xeb, 0x11, 0xc5, 0x76, 0x3a, 0x40, 0xe2, 0xb2, 0xdb, 0xf3,
	0xef, 0x8f, 0xfd, 0x7b, 0x7e, 0x8f, 0xbc, 0xd2, 0xa0, 0x34, 0x2d, 0x31, 0x2d, 0x14, 0xe5, 0x4b,
	0x41, 0x57, 0x27, 0x7c, 0xb1, 0xbc, 0xe4, 0x27, 0x06, 0x4a, 0x2a, 0x50, 0x58, 0x57, 0x29, 0xa8,
	0x68, 0x59, 0xa1, 0xc6, 0x60, 0xaf, 0x51, 0x0b, 0x99, 0x47, 0x0a, 0x17, 0x18, 0x09, 0x1c, 0x1f,
	0x80, 0x5c, 0xe1, 0x8d, 0x75, 0x9e, 0xd2, 0x4c, 0xa8, 0x14, 0x57, 0x50, 0xdd, 0x58, 0xf9, 0xf8,
	0x20, 0x47, 0xcc, 0x17, 0x60, 0x68, 0x2e, 0x25, 0x6a, 0xae, 0x05, 0x4a, 0x77, 0xd9, 0x78, 0x94,
	0x63, 0x8e, 0xa6, 0xa4, 0x4d, 0xe5, 0xd0, 0x00, 0xae, 0xb5, 0x05, 0xe1, 0x5a, 0x3b, 0xec, 0xb0,
	0x79, 0xee, 0x75, 0x21, 0xb4, 0x8b, 0x48, 0x4b, 0xd0, 0x3c, 0xe3, 0x9a, 0xb7, 0xef, 0xfc, 0xcb,
	0x2b, 0xcd, 0x75, 0xad, 0xfe, 0xe7, 0x6e, 0xcf, 0x96, 0x3f, 0xfe, 0xde, 0x21, 0xbb, 0x17, 0x98,
	0x16, 0xb1, 0x6b, 0x36, 0x78, 0x4b, 0xba, 0xf6, 0x82, 0xb0, 0x3b, 0xf1, 0xa6, 0x4f, 0x4e, 0x47,
	0x51, 0x8a, 0x15, 0xb4, 0x3d, 0x47, 0x9f, 0x0c, 0xc7, 0x7a, 0x6b, 0xe6, 0xfd, 0xb8, 0x3b, 0xda,
	0x8a, 0x9d, 0x38, 0x38, 0x23, 0xfd, 0x36, 0x57, 0xd8, 0x33, 0xc6, 0x67, 0x7f, 0x1b, 0x2f, 0x1c,
	0xcb, 0x7c, 0xe3, 0xdb, 0xa8, 0x83, 0x17, 0xc4, 0x37, 0x2e, 0x6f, 0xe2, 0x4d, 0x07, 0x6c, 0xf8,
	0xeb, 0xee, 0x68, 0x60, 0xba, 0xfb, 0xaa, 0x50, 0xc6, 0x0f, 0x65, 0xf0, 0x92, 0xec, 0x29, 0x2c,
	0x21, 0xc9, 0xea, 0x72, 0x96, 0xcc, 0x05, 0x2c, 0xb2, 0x30, 0x33, 0x96, 0xed, 0x35, 0xf3, 0xe2,
	0x61, 0xc3, 0xbd, 0xaf, 0xcb, 0xd9, 0x79, 0xc3, 0x04, 0xcf, 0xc9, 0x00, 0x25, 0xe0, 0x3c, 0x41,
	0x09, 0xe1, 0x76, 0x23, 0xfb, 0xb0, 0x15, 0xf7, 0x0d, 0xf4, 0x51, 0xc2, 0x03, 0xad, 0xaf, 0x30,
	0xec, 0x4c, 0xbc, 0x69, 0x7f, 0x43, 0x7f, 0xbe, 0xc2, 0x77, 0xfb, 0xb7, 0xf7, 0xbe, 0x4f, 0x3a,
	0x65, 0x71, 0x7b, 0xef, 0xf7, 0x82, 0x1d, 0xb3, 0x20, 0x6c, 0x9f, 0x3c, 0x6d, 0x16, 0x20, 0xb1,
	0x46, 0x13, 0x40, 0x1d, 0x2b, 0xb2, 0x7b, 0xce, 0x0b, 0xd8, 0xfc, 0xde, 0x88, 0xec, 0xa4, 0x58,
	0x4b, 0x6d, 0xba, 0x19, 0xc6, 0xf6, 0xf0, 0xf8, 0xcf, 0x69, 0x93, 0xcc, 0x5d, 0x92, 0x39, 0x2f,
	0x40, 0xb1, 0xb3, 0x35, 0xf3, 0xbe, 0xfd, 0x3c, 0xf4, 0xbe, 0xd0, 0x5c, 0xe8, 0xcb, 0x7a, 0x16,
	0xa5, 0x58, 0xda, 0xb9, 0x0a, 0xdc, 0xcc, 0x97, 0xfe, 0xb1, 0xdb, 0xed, 0x5e, 0xcf, 0xba, 0x66,
	0xe8, 0x6f, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0xdc, 0x2c, 0xb9, 0x76, 0xf9, 0x02, 0x00, 0x00,
}

func (this *MockResource) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MockResource)
	if !ok {
		that2, ok := that.(MockResource)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Status.Equal(&that1.Status) {
		return false
	}
	if !this.Metadata.Equal(&that1.Metadata) {
		return false
	}
	if this.Data != that1.Data {
		return false
	}
	if this.SomeDumbField != that1.SomeDumbField {
		return false
	}
	if that1.TestOneofFields == nil {
		if this.TestOneofFields != nil {
			return false
		}
	} else if this.TestOneofFields == nil {
		return false
	} else if !this.TestOneofFields.Equal(that1.TestOneofFields) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *MockResource_OneofOne) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MockResource_OneofOne)
	if !ok {
		that2, ok := that.(MockResource_OneofOne)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.OneofOne != that1.OneofOne {
		return false
	}
	return true
}
func (this *MockResource_OneofTwo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MockResource_OneofTwo)
	if !ok {
		that2, ok := that.(MockResource_OneofTwo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.OneofTwo != that1.OneofTwo {
		return false
	}
	return true
}
func (this *FakeResource) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FakeResource)
	if !ok {
		that2, ok := that.(FakeResource)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Count != that1.Count {
		return false
	}
	if !this.Metadata.Equal(&that1.Metadata) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
