name: PR Auto Labeling
on:
  pull_request:
    types:
      - opened
jobs:
  add-label:
    name: Add `keep pr updated` Label
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: christianvuerings/add-labels@v1
        with:
          labels: |
            keep pr updated
        env:
          GITHUB_TOKEN: ${{ github.token }}
