name: PR Auto Labeling
on:
  pull_request:
    types:
      - opened
jobs:
  add-label:
    name: Add `keep pr updated` Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: christianvuerings/add-labels@v1
        with:
          labels: |
            keep pr updated
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}