name: pull_request

on:
  push:
    branches:
      - "main"
  pull_request: { }

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
      - name: Cancel Previous Actions
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Set up Go (derived from go.mod)
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - uses: engineerd/setup-kind@v0.5.0
        with:
          skipClusterCreation: "true"
          version: v0.18.0
      - name: Install Protoc
        uses: arduino/setup-protoc@master
        with:
          version: "3.6.1"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: azure/setup-kubectl@v1
        with:
          version: v1.26.4
      - uses: azure/setup-helm@v3
        with:
          version: v3.11.2
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Set up test cluster
        run: |
          kind create cluster --image "kindest/node:v1.26.3@sha256:61b92f38dff6ccc29969e7aa154d34e38b89443af1a2c14e6cfbd2df6419c66f"
      - name: Run Tests
        run: |
          make update-all tests -c
        env:
          RUN_KUBE_TESTS: 1
          RUN_CONSUL_TESTS: 1
          RUN_VAULT_TESTS: 1
